Feature reduced hierarchy transform update
FishingCactus/openfl pull request #118
Opened 2016-12-16 16:52 UTC by rams3s

2016-12-27 10:33 UTC, NuclearCookie requested changes

2016-12-27 10:33 UTC, NuclearCookie commented on format/swf/lite/MovieClip.hx
>  		// :TODO: use dirty flag if need to update __9SliceBitmap
you adressed these todos

2016-12-27 10:33 UTC, NuclearCookie commented on openfl/display/BitmapData.hx
> +			var copy = new BitmapData (Reflect.getProperty (source, "__width"), Reflect.getProperty (source, "__height"), true, 0);
use Reflect.getField now instead of getProperty

2016-12-27 10:33 UTC, NuclearCookie commented on openfl/display/BitmapData.hx
> +			var copy = new BitmapData (Reflect.getProperty (source, "__width"), Reflect.getProperty (source, "__height"), true, 0);
same here

2016-12-27 10:34 UTC, NuclearCookie commented
Also, When reusing a 9slice graphic, I am experiencing issues with transparency. ( state does not seem to be reset ).

2016-12-27 13:01 UTC, NuclearCookie commented
Blend modes also seem broken ( multiply )

2016-12-27 13:06 UTC, NuclearCookie commented on format/swf/lite/MovieClip.hx
>  		if (__symbol != null && __symbol.scalingGridRect != null && __9SliceBitmap == null) {
This condition can be avoided if you look at the place this function is called

2016-12-27 14:56 UTC, NuclearCookie commented on openfl/_internal/renderer/RenderSession.hx
> +	public function pushRenderTargetBaseTransform (source:Dynamic, renderTargetBaseTransform:Matrix) {
Source could be IBitmapDrawable

2016-12-27 15:08 UTC, NuclearCookie commented on format/swf/lite/MovieClip.hx
re-add the bounds to the pool

2016-12-27 16:17 UTC, NuclearCookie commented
I am experiencing issues with cached as bitmap. If I use it, masks seem to be ignored. 
First thought:
When drawing the mask, we used to update all the children https://github.com/FishingCactus/openfl/pull/118/files#diff-2b58ec07f66353241b751100e39589a9L181
This will have to be added somewhere

2016-12-28 10:12 UTC, rams3s commented on format/swf/lite/MovieClip.hx
>  		if (__symbol != null && __symbol.scalingGridRect != null && __9SliceBitmap == null) {
not exactly the same test

2016-12-28 10:20 UTC, rams3s commented on format/swf/lite/MovieClip.hx
good catch ;)

2016-12-28 10:22 UTC, rams3s commented on openfl/display/BitmapData.hx
> +			var copy = new BitmapData (Reflect.getProperty (source, "__width"), Reflect.getProperty (source, "__height"), true, 0);
true

2016-12-28 10:26 UTC, rams3s commented on openfl/display/BitmapData.hx
> +			var copy = new BitmapData (Reflect.getProperty (source, "__width"), Reflect.getProperty (source, "__height"), true, 0);
true again

2016-12-28 10:30 UTC, rams3s commented on openfl/_internal/renderer/RenderSession.hx
> +	public function pushRenderTargetBaseTransform (source:Dynamic, renderTargetBaseTransform:Matrix) {
done

2017-01-05 14:25 UTC, NuclearCookie commented
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 139 at r11](https://reviewable.io:443/reviews/fishingcactus/openfl/118#-K_j0EnXsTSxRH646Amy:-K_j0EnXsTSxRH646Amz:bmetkql) ([raw file](https://github.com/fishingcactus/openfl/blob/155f8c632069518db6cfee8dfcc22985e132ea7c/format/swf/lite/MovieClip.hx#L139)):*
> if (!__useSeparateRenderScaleTransform) {
> 			
> 			for( i in 0 ... numChildren ){
> 				var child = getChildAt(i);
> 				child.__useSeparateRenderScaleTransform = false;
> 			}
> 			
> 		}
>  

What about adding a child using AddChild ? Don't we have to do the same check at that moment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/118)*
<!-- Sent from Reviewable.io -->

2017-01-11 10:43 UTC, rams3s commented
Review status: 0 of 27 files reviewed at latest revision, 5 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 716 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/118#-KZ7YFfRCclnsHq5FDmu-r1-716:-KaC6y2w-9YV91rkWAi5:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/ee1fed5116e51c3d60a686020003cbc516600955/format/swf/lite/MovieClip.hx#L716)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

you adressed these todos
</blockquote></details>

Done.

---

*[format/swf/lite/MovieClip.hx, line 139 at r11](https://reviewable.io:443/reviews/fishingcactus/openfl/118#-K_j0EnXsTSxRH646Amy:-KaBqTf6KRWyC3iraVqu:b-hm308m) ([raw file](https://github.com/fishingcactus/openfl/blob/155f8c632069518db6cfee8dfcc22985e132ea7c/format/swf/lite/MovieClip.hx#L139)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> if (!__useSeparateRenderScaleTransform) {
> 			
> 			for( i in 0 ... numChildren ){
> 				var child = getChildAt(i);
> 				child.__useSeparateRenderScaleTransform = false;
> 			}
> 			
> 		}
>  

What about adding a child using AddChild ? Don't we have to do the same check at that moment?

</blockquote></details>

Shouldn't happen (__useSeparateRenderScaleTransform is false for Bitmaps and 9 slice shapes only) but moved this code to addChild for safety. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/118)*
<!-- Sent from Reviewable.io -->

2017-01-12 08:19 UTC, merged